using Cufet.Compiler;
using Cufet.Interpreter;
using Xunit;
using CufetInterpreter = Cufet.Interpreter.Interpreter;
using CufetLexer = Cufet.Lexer.Lexer;
namespace Cufet.Compiler.Tests;

/// <summary>One slice of the pipeline oracle suite — see PipelineTestBase for why it is split.</summary>
///
/// ★ These close a real divergence, not a gap in coverage. `"héllo" in uppercase` used to be HÉLLO
/// interpreted and HéLLO compiled, because the interpreter called .NET's ToUpperInvariant and the
/// generated C called toupper() once per byte — so everything outside A–Z passed straight through.
/// It was filed as a documented exception for a while, next to pow's last ULP and filesystem
/// enumeration order; but that clause ends "two well-defined behaviours differing is never in that
/// category", and Unicode says exactly what uppercase é is. The exception was covering a missing
/// implementation.
///
/// ★ The fix is one table read by BOTH backends (CaseTableData, generated by tools/gen-case-table.cs),
/// not two implementations kept in step. That is why there is no "do the backends still agree about
/// Unicode" test here beyond the ordinary Interpret-equals-Compile assertion every case makes: they
/// agree by construction, and the thing worth testing is that the table itself is right.
public class PipelineCaseTests : PipelineTestBase
{
    [Fact]
    public void AccentedLatin_CasesTheSameOnBothBackends()
    {
        // The original divergence, in the form it was found.
        const string src = """
            State "héllo" in uppercase.
            State "HÉLLO" in lowercase.
            State "Grüße, Æsop" in uppercase.
            State "ÀÉÎÕÜ" in lowercase.
            """;
        Assert.Equal(InterpretRaw(src), CompileRaw(src));
        Assert.Equal("HÉLLO\nhéllo\nGRÜßE, ÆSOP\nàéîõü", Interpret(src));
    }

    [Fact]
    public void NonLatinScripts_Case()
    {
        // Greek and Cyrillic are the two big alphabetic scripts past Latin, and both are pure
        // stride-2 or constant-delta runs — the shape the table's encoding is built around.
        const string src = """
            State "ΑΣΠΙΔΑ" in lowercase.
            State "μεταφορά" in uppercase.
            State "МОСКВА" in lowercase.
            State "тбилиси" in uppercase.
            """;
        Assert.Equal(InterpretRaw(src), CompileRaw(src));
        Assert.Equal("ασπιδα\nΜΕΤΑΦΟΡΆ\nмосква\nТБИЛИСИ", Interpret(src));
    }

    [Fact]
    public void AboveTheBasicMultilingualPlane_Cases()
    {
        // ★ Deseret needs a surrogate pair in the interpreter and a four-byte sequence in the
        // compiled runtime, so this is the one case where the two backends' encodings differ in
        // shape rather than only in value. 260 of the table's uppercase mappings live up here.
        const string src = """
            State "𐐨𐐩𐐪" in uppercase.
            State "𐐀𐐁𐐂" in lowercase.
            """;
        Assert.Equal(InterpretRaw(src), CompileRaw(src));
        Assert.Equal("𐐀𐐁𐐂\n𐐨𐐩𐐪", Interpret(src));
    }

    [Fact]
    public void CharactersWithNoMapping_AreLeftAlone()
    {
        // ★ The deliberate non-changes, and the reason the roadmap's "ß → SS makes text grow" worry
        // does not apply. This is SIMPLE case mapping: `ß` stays `ß` rather than becoming SS, the
        // `ﬁ` ligature stays whole, and invariant culture leaves the Turkish pair ı/İ alone instead
        // of picking a side. Nothing here ever changes length in characters.
        const string src = """
            State "straße" in uppercase.
            State "ﬁancé" in uppercase.
            State "ı and İ" in uppercase.
            State "ı and İ" in lowercase.
            State "日本語 ← 한글 ← العربية" in uppercase.
            State "123 !@# ∑ ∀" in lowercase.
            """;
        Assert.Equal(InterpretRaw(src), CompileRaw(src));
        Assert.Equal(
            "STRAßE\nﬁANCÉ\nı AND İ\nı and İ\n日本語 ← 한글 ← العربية\n123 !@# ∑ ∀",
            Interpret(src));
    }

    [Fact]
    public void TitlecaseCharacters_UpperAndLowerToDifferentThings()
    {
        // ǅ (U+01C5) is a TITLECASE letter: it has both an uppercase (Ǆ) and a lowercase (ǆ) form,
        // so it is one of the few code points appearing in both halves of the table with unequal
        // deltas. A run-length encoder that assumed one delta per code point would break here.
        const string src = """
            State "ǅungla" in uppercase.
            State "ǅungla" in lowercase.
            State "Ǆ" in lowercase.
            State "ǆ" in uppercase.
            """;
        Assert.Equal(InterpretRaw(src), CompileRaw(src));
        Assert.Equal("ǄUNGLA\nǆungla\nǆ\nǄ", Interpret(src));
    }

    [Fact]
    public void CasingThatChangesByteLength_RoundTrips()
    {
        // ★ The compiled runtime sizes its output at twice the input because a character can gain a
        // byte: U+023F is two bytes and uppercases to U+2C7E, which is three. U+017F goes the other
        // way, two bytes down to one. Both directions in one program, then measured, so a buffer
        // that was sized per byte rather than per character would fail here rather than silently
        // truncating.
        const string src = """
            Define grew as "ȿȾ" in uppercase.
            Define shrank as "ſ" in uppercase.
            State grew.
            State shrank.
            State the length of grew.
            State the length of shrank.
            """;
        Assert.Equal(InterpretRaw(src), CompileRaw(src));

        // ⚠ Read the code points, not the glyphs — the first two characters of the expectation are
        // U+2C7E then U+023E, which most fonts draw almost identically. The input is U+023F U+023E:
        // U+023F is two bytes and uppercases to U+2C7E at three, which is the growth the buffer
        // sizing has to survive, while U+023E is already uppercase and stays put. U+017F goes the
        // other way, two bytes down to the single byte of S.
        Assert.Equal("ⱾȾ\nS\n2\n1", Interpret(src));
    }

    [Fact]
    public void CasingComposesWithTheRestOfTheTextToolkit()
    {
        // Casing is not a special form — it chains with trim/replace/split like anything else, and
        // the compiled version has to keep working now that it allocates differently.
        const string src = """
            Define raw as "  Ünïcödé Tëxt  ".
            State raw trimmed in uppercase.
            State replace "ë" with "e" in (raw trimmed in lowercase).
            For each word in ("ÉIN ZWÉI DRÉI" in lowercase) split by " ", repeat:
                State word.
            Done.
            """;
        Assert.Equal(InterpretRaw(src), CompileRaw(src));
        Assert.Equal("ÜNÏCÖDÉ TËXT\nünïcödé text\néin\nzwéi\ndréi", Interpret(src));
    }

    [Fact]
    public void CasingAnEmptyOrAsciiOnlyText_IsUnchangedInShape()
    {
        // The overwhelmingly common path, and the one with a fast branch in both implementations.
        const string src = """
            State "" in uppercase.
            State "" in lowercase.
            State "Hello, World! 42" in uppercase.
            State "Hello, World! 42" in lowercase.
            State the length of ("" in uppercase).
            """;
        Assert.Equal(InterpretRaw(src), CompileRaw(src));
        Assert.Equal("\n\nHELLO, WORLD! 42\nhello, world! 42\n0", Interpret(src));
    }

    [Fact]
    public void TheCaseTable_IsEmittedOnlyWhenTheProgramCasesText()
    {
        // ★ The table is ~15 KB of the runtime that gets pasted into EVERY generated file, so it is
        // gated like the math, chance and process runtimes are. This is the control on that gate:
        // without it the cost would be silent and permanent, paid by every program that never cases
        // a character.
        const string cases = """
            State "é" in uppercase.
            """;
        const string doesNot = """
            State "é".
            """;

        Assert.Contains("cufet_case_upper", EmitC(cases));
        Assert.DoesNotContain("cufet_case_upper", EmitC(doesNot));
        Assert.DoesNotContain("cufet_str_case", EmitC(doesNot));
    }

    private static string EmitC(string source)
    {
        var tokens = new CufetLexer(source).Tokenize();
        var program = new Parser(tokens).Parse();
        new TypeChecker().Check(program);
        return new CodeGenerator().Generate(program);
    }
}
