using System.Text;

namespace Cufet.Compiler;

/// <summary>
/// Splits the fixed C runtime into a compilable translation unit plus the header a generated
/// program needs to call into it.
/// </summary>
/// <remarks>
/// <para>
/// ★ The runtime used to be pasted into every generated file — 955 lines and ~50 KB before the
/// program's own code started, which measured at 79% of a typical output and 98.9% of a small one.
/// It also cost the whole build: gcc spent ~415 ms on it and ~0 ms on `fibonacci`'s actual 578
/// bytes, so every build recompiled the same runtime from scratch.
/// </para>
/// <para>
/// ★★ The correctness win matters more than the speed. A single file meant every runtime symbol had
/// to be emitted above its first use, so the emitter carried an ordering rule per block — and three
/// separate defects in one session were all "symbol emitted above its own declaration", each fixed
/// by MOVING code rather than by fixing a rule. Once the runtime is its own unit, the generated file
/// no longer contains the definitions it depends on and that entire class stops existing.
/// </para>
/// <para>
/// The header is DERIVED from the runtime source rather than maintained beside it, because a header
/// maintained by hand is a second copy of 112 signatures that drifts the first time someone adds a
/// helper. Deriving it means a new runtime function is exported automatically and cannot be
/// forgotten. The extraction is deliberately narrow — it handles the shapes this runtime actually
/// uses and nothing else — and it is verified the only way that means anything: by compiling the
/// whole example corpus in split form and checking the binaries still produce identical output.
/// </para>
/// </remarks>
public static class RuntimeSplit
{
    public const string HeaderFileName = "cufet-runtime.h";
    public const string SourceFileName = "cufet-runtime.c";

    /// <summary>The header and the .c body for a runtime source that was emitted as one blob.</summary>
    public static (string Header, string Source) Split(string runtime)
    {
        var header = new StringBuilder();
        var source = new StringBuilder();

        header.AppendLine("/* Generated by cufet — the fixed runtime's interface. Do not edit. */");
        header.AppendLine("#ifndef CUFET_RUNTIME_H");
        header.AppendLine("#define CUFET_RUNTIME_H");
        header.AppendLine();

        source.AppendLine("/* Generated by cufet — the fixed runtime. Do not edit. */");
        source.AppendLine($"#include \"{HeaderFileName}\"");
        source.AppendLine();

        var lines = runtime.Replace("\r\n", "\n").Split('\n');
        int i = 0;
        while (i < lines.Length)
        {
            string line = lines[i];
            string trimmed = line.TrimStart();

            // ⚠ Preprocessor lines go to BOTH files, verbatim and in order.
            //
            // Sending them only to the header looked right and was badly wrong: the SIGINT substrate
            // is `#if defined(__unix__) ... #else ... #endif` around two complete implementations,
            // so hoisting the guards left BOTH bodies in the source unguarded — "redefinition of
            // cufet_interrupted", and the POSIX branch demanding sigaction on a Windows build.
            // Copying them to both keeps each file's conditionals balanced and selecting the same
            // branch: the header gets that branch's declarations, the source gets its definitions.
            //
            // Duplicating `#include` and `#define` between the two is harmless — include guards
            // handle the first, and an identical macro redefinition is legal C.
            if (trimmed.StartsWith('#'))
            {
                header.AppendLine(line);
                source.AppendLine(line);
                i++;
                continue;
            }

            // Comments and blank lines outside a construct are structure, not code — keep them with
            // the source, which is the copy a person reads.
            if (trimmed.Length == 0 || trimmed.StartsWith("/*") || trimmed.StartsWith("//"))
            {
                var (commentText, afterComment) = TakeComment(lines, i);
                source.Append(commentText);
                i = afterComment;
                continue;
            }

            var (construct, next) = TakeConstruct(lines, i);
            i = next;
            Emit(construct, header, source);
        }

        header.AppendLine();
        header.AppendLine("#endif /* CUFET_RUNTIME_H */");
        return (header.ToString(), source.ToString());
    }

    /// <summary>
    /// Every function the <paramref name="source"/> half defines — which is exactly the set a
    /// compiled runtime object must export for a generated program to link against it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// ★★ This exists so <see cref="RuntimeCache"/> can ASK THE LINKER whether an object it is
    /// about to reuse really defines the runtime, instead of trusting that a file at the right
    /// path is the right file. A content-addressed key cannot see contents: it proves what the
    /// object was BUILT FROM and says nothing about what it turned out to hold.
    /// </para>
    /// <para>
    /// ⚠⚠ MEASURED 2026-09-05, which is what makes this worth its weight: an object compiled from
    /// EMPTY source is a perfectly well-formed 936-byte ELF with zero defined symbols, and the
    /// linker accepts it without a word — the program then fails with `undefined reference to
    /// cufet_dec_lit` and friends, which reads as a code-generator regression and is not one. A
    /// merely TRUNCATED object is caught already, because `ld` says `file too short` instead. So
    /// that exact wording identifies the symbol-poor case and nothing else.
    /// </para>
    /// <para>
    /// ⚠ Functions only. The source half exports variables too, but a name is far harder to read
    /// out of `const cufet_u256 CUFET_DEC_MAX = {…}` than out of a prototype — and the failure
    /// this guards against is an object that defines NOTHING, which the first function catches.
    /// Widening it would buy nothing and add a second shape to get wrong.
    /// </para>
    /// </remarks>
    public static IReadOnlyList<string> DefinedFunctions(string source)
    {
        var names = new List<string>();
        var lines = source.Replace("\r\n", "\n").Split('\n');
        int i = 0;

        while (i < lines.Length)
        {
            string trimmed = lines[i].TrimStart();

            if (trimmed.StartsWith('#')) { i++; continue; }

            if (trimmed.Length == 0 || trimmed.StartsWith("/*") || trimmed.StartsWith("//"))
            {
                (_, i) = TakeComment(lines, i);
                continue;
            }

            var (construct, next) = TakeConstruct(lines, i);
            i = next;

            string text = construct.Trim();

            // ⚠ `static` is skipped, and that is the point rather than an oversight. This answers
            // "what may a generated PROGRAM call", and a program can only call what the derived
            // header declares — which is never a static. Emit strips `static` from everything it
            // exports, so nothing real is lost here; what is excluded is a helper private to the
            // runtime, and naming one in the probe would ask the linker for a symbol that is
            // deliberately not there.
            if (text.StartsWith("static ", StringComparison.Ordinal)) continue;

            // The same test Emit uses to tell a function body from an aggregate initializer: a
            // body's brace follows the parameter list's `)`, an initializer's follows `=`.
            int brace = IndexOfTopLevel(text, '{');
            if (brace < 0 || LastNonSpaceBefore(text, brace) != ')') continue;

            string? name = FunctionNameOf(text[..brace]);
            if (name != null) names.Add(name);
        }

        return names;
    }

    // The identifier immediately before the top-level `(` — `void cufet_dec_lit(const char *s, …)`
    // gives `cufet_dec_lit`. Narrow on purpose, like the rest of this file: it reads the shapes
    // this runtime uses and returns null rather than a guess for anything else.
    private static string? FunctionNameOf(string prototype)
    {
        int paren = IndexOfTopLevel(prototype, '(');
        if (paren <= 0) return null;

        int end = paren - 1;
        while (end >= 0 && char.IsWhiteSpace(prototype[end])) end--;

        int start = end;
        while (start >= 0 && (prototype[start] == '_' || char.IsLetterOrDigit(prototype[start]))) start--;
        start++;

        if (start > end) return null;
        string name = prototype[start..(end + 1)];
        return char.IsDigit(name[0]) ? null : name;
    }

    // A comment or run of blank lines, returned whole so a block comment is never split down the
    // middle by the construct scanner.
    private static (string Text, int Next) TakeComment(string[] lines, int start)
    {
        var text = new StringBuilder();
        int i = start;
        bool inBlock = false;
        do
        {
            string line = lines[i];
            text.AppendLine(line);
            if (line.Contains("/*") && !line.Contains("*/")) inBlock = true;
            else if (inBlock && line.Contains("*/")) inBlock = false;
            i++;
        } while (inBlock && i < lines.Length);
        return (text.ToString(), i);
    }

    // One top-level construct: everything up to a `;` at depth zero (a declaration) or a balanced
    // `{...}` (a definition).
    //
    // ⚠ It must skip COMMENTS as well as literals. The runtime is commented in English prose, and
    // an apostrophe in `don't` reads as the start of a character literal to anything that only
    // tracks quotes — which silently swallows every construct after it, so the header comes out
    // missing two thirds of its prototypes and the failure surfaces far from its cause.
    private static (string Text, int Next) TakeConstruct(string[] lines, int start)
    {
        var text = new StringBuilder();
        int i = start, braces = 0, parens = 0;
        bool started = false, inString = false, inChar = false, inBlockComment = false;

        while (i < lines.Length)
        {
            string line = lines[i];
            text.AppendLine(line);
            i++;

            for (int c = 0; c < line.Length; c++)
            {
                char ch = line[c];

                if (inBlockComment)
                {
                    if (ch == '*' && c + 1 < line.Length && line[c + 1] == '/') { inBlockComment = false; c++; }
                    continue;
                }
                if (inString) { if (ch == '\\') c++; else if (ch == '"') inString = false; continue; }
                if (inChar) { if (ch == '\\') c++; else if (ch == '\'') inChar = false; continue; }

                if (ch == '/' && c + 1 < line.Length && line[c + 1] == '/') break;            // rest of line
                if (ch == '/' && c + 1 < line.Length && line[c + 1] == '*') { inBlockComment = true; c++; continue; }

                switch (ch)
                {
                    case '"': inString = true; break;
                    case '\'': inChar = true; break;
                    case '(': parens++; break;
                    case ')': parens--; break;
                    case '{': braces++; started = true; break;
                    case '}': braces--; break;
                    case ';' when braces == 0 && parens == 0 && !started:
                        return (text.ToString(), i);                     // a declaration
                }
            }

            if (started && braces == 0) return (text.ToString(), i);     // a definition
        }
        return (text.ToString(), i);
    }

    private static void Emit(string construct, StringBuilder header, StringBuilder source)
    {
        string text = construct.TrimEnd();
        string flat = text.TrimStart();

        // A typedef is pure interface: the program needs the type, nothing needs a definition.
        if (flat.StartsWith("typedef"))
        {
            header.AppendLine(text);
            return;
        }

        bool isStatic = flat.StartsWith("static ");
        string exported = isStatic ? StripLeading(text, "static ") : text;

        // ⚠ A `{` alone does not mean a function body — `static const cufet_u256 CUFET_DEC_MAX =
        // {...};` is an aggregate initializer, and treating it as one produced the nonsense
        // `const cufet_u256 CUFET_DEC_MAX =;` in the header. A body's brace follows the parameter
        // list's `)`; an initializer's follows `=`.
        int brace = IndexOfTopLevel(exported, '{');
        if (brace >= 0 && LastNonSpaceBefore(exported, brace) == ')')
        {
            // A function definition. The header takes everything up to the body as a prototype; the
            // body itself goes to the source with `static` dropped so the program can link to it.
            header.AppendLine(exported[..brace].TrimEnd() + ";");
            source.AppendLine(exported);
            return;
        }

        // A declaration. A forward function declaration is already a prototype and needs no
        // definition; anything else is a variable, which the header re-declares as `extern` with its
        // initializer removed — an initializer in a header would define the object in every unit
        // that included it.
        if (LooksLikeFunctionDeclaration(exported))
        {
            header.AppendLine(exported);
            return;
        }

        header.AppendLine("extern " + WithoutInitializer(exported));
        source.AppendLine(exported);
    }

    private static char LastNonSpaceBefore(string text, int index)
    {
        for (int i = index - 1; i >= 0; i--)
            if (!char.IsWhiteSpace(text[i])) return text[i];
        return '\0';
    }

    private static string StripLeading(string text, string prefix)
    {
        int at = text.IndexOf(prefix, StringComparison.Ordinal);
        return at < 0 ? text : text.Remove(at, prefix.Length);
    }

    // ★ `(*` is the tell that separates a function DECLARATION from a function-POINTER VARIABLE.
    // `static void (*cufet_um_fn[N])(void*);` has parentheses and an identifier and would otherwise
    // read as a prototype — declaring it as one compiles, then fails to link against a symbol that
    // was never a function.
    private static bool LooksLikeFunctionDeclaration(string text) =>
        IndexOfTopLevel(text, '(') > 0 && !text.Contains("(*") && !text.Contains('=');

    private static string WithoutInitializer(string text)
    {
        int eq = IndexOfTopLevel(text, '=');
        return eq < 0 ? text : text[..eq].TrimEnd() + ";";
    }

    // The first occurrence of `target` that is not inside a string, a character literal, or — for
    // anything but '(' itself — a parenthesised group.
    private static int IndexOfTopLevel(string text, char target)
    {
        int parens = 0;
        bool inString = false, inChar = false;
        for (int i = 0; i < text.Length; i++)
        {
            char ch = text[i];
            if (ch == '\\') { i++; continue; }
            if (inString) { if (ch == '"') inString = false; continue; }
            if (inChar) { if (ch == '\'') inChar = false; continue; }
            if (ch == '"') { inString = true; continue; }
            if (ch == '\'') { inChar = true; continue; }
            if (ch == target && parens == 0) return i;
            if (ch == '(') parens++;
            else if (ch == ')') parens--;
        }
        return -1;
    }
}
