// Generates src/Interpreter/CaseTableData.cs — the single case-mapping table BOTH backends read.
//
// Run it with:  dotnet run tools/gen-case-table.cs
//
// ★ Why a generated table instead of each backend casing text its own way. The interpreter used to
// call .NET's ToUpperInvariant and the compiled runtime used C's toupper() per byte, so `"héllo" in
// uppercase` was HÉLLO interpreted and HéLLO compiled — a divergence, and the no-divergence rule
// says two well-defined behaviours differing is never an acceptable exception. Generating the C
// table from .NET would have made them agree at generation time only: the interpreter would still
// be asking ICU at run time, so a .NET upgrade carrying a newer Unicode version silently reopens
// the gap and a test only tells you after it is already true. One table read by both backends makes
// the drift IMPOSSIBLE rather than detectable, and pins Cufet's casing to a stated Unicode version
// instead of to whichever .NET the user happens to have installed.
//
// ★ The mapping is 1:1 — every one of the 1,114,112 code points, no exceptions. ToUpperInvariant is
// SIMPLE case mapping, so `ß` stays `ß`, the `ﬁ` ligature stays `ﬁ`, and invariant culture leaves
// the Turkish pair `ı`/`İ` alone rather than picking a side. The `ß` → `SS` growth that full case
// mapping would force does not arise here, which is why neither backend ever has to change a
// string's length in code points.

using System.Text;

const string OutPath = "src/Interpreter/CaseTableData.cs";

// ── Collect the raw 1:1 mappings ────────────────────────────────────────────────────────────────
var upper = new List<(int cp, int to)>();
var lower = new List<(int cp, int to)>();

for (int cp = 0; cp <= 0x10FFFF; cp++)
{
    if (cp >= 0xD800 && cp <= 0xDFFF) continue;          // lone surrogates are not characters
    string s = char.ConvertFromUtf32(cp);
    string u = s.ToUpperInvariant();
    string l = s.ToLowerInvariant();
    if (u != s)
    {
        if (CodePointCount(u) != 1) throw new Exception($"U+{cp:X4} uppercases to {CodePointCount(u)} code points — the 1:1 assumption this table is built on no longer holds.");
        upper.Add((cp, char.ConvertToUtf32(u, 0)));
    }
    if (l != s)
    {
        if (CodePointCount(l) != 1) throw new Exception($"U+{cp:X4} lowercases to {CodePointCount(l)} code points — the 1:1 assumption this table is built on no longer holds.");
        lower.Add((cp, char.ConvertToUtf32(l, 0)));
    }
}

var upperRuns = BuildRuns(upper);
var lowerRuns = BuildRuns(lower);

// ── Verify, using the SAME binary search the C runtime and the C# lookup will use ───────────────
for (int cp = 0; cp <= 0x10FFFF; cp++)
{
    if (cp >= 0xD800 && cp <= 0xDFFF) continue;
    string s = char.ConvertFromUtf32(cp);
    int gotU = Lookup(upperRuns, cp), gotL = Lookup(lowerRuns, cp);
    int wantU = char.ConvertToUtf32(s.ToUpperInvariant(), 0);
    int wantL = char.ConvertToUtf32(s.ToLowerInvariant(), 0);
    if (gotU != wantU) throw new Exception($"upper U+{cp:X4}: got U+{gotU:X4}, want U+{wantU:X4}");
    if (gotL != wantL) throw new Exception($"lower U+{cp:X4}: got U+{gotL:X4}, want U+{wantL:X4}");
}

// ★ Per-code-point agreement is not enough on its own. A culture-aware caser can be CONTEXTUAL —
// Greek final sigma is the standard example, where Σ lowercases to ς only at the end of a word — and
// a contextual rule would make a table wrong for whole strings while every single character passed.
// Invariant culture is documented as non-contextual; this fuzzes multi-code-point strings to hold
// .NET to that, so the table is verified the way it is actually used.
var rng = new Random(20260813);
var alphabet = upper.Select(x => x.cp).Concat(lower.Select(x => x.cp))
                    .Concat([0x20, 0x3A3, 0x3C2, 0x3C3, 0x69, 0x131, 0x130, 0xDF]).Distinct().ToArray();
for (int trial = 0; trial < 200_000; trial++)
{
    var sb = new StringBuilder();
    int n = rng.Next(1, 9);
    for (int i = 0; i < n; i++) sb.Append(char.ConvertFromUtf32(alphabet[rng.Next(alphabet.Length)]));
    string s = sb.ToString();
    string gotU = MapString(upperRuns, s), gotL = MapString(lowerRuns, s);
    if (gotU != s.ToUpperInvariant()) throw new Exception($"upper string mismatch on {Escape(s)}: got {Escape(gotU)}, want {Escape(s.ToUpperInvariant())}");
    if (gotL != s.ToLowerInvariant()) throw new Exception($"lower string mismatch on {Escape(s)}: got {Escape(gotL)}, want {Escape(s.ToLowerInvariant())}");
}

// ── Emit ────────────────────────────────────────────────────────────────────────────────────────
var outFile = new StringBuilder();
outFile.Append($$"""
// <auto-generated>
//     Generated by tools/gen-case-table.cs — DO NOT EDIT BY HAND.
//     Regenerate with:  dotnet run tools/gen-case-table.cs
// </auto-generated>
//
// The case-mapping table BOTH backends read: the interpreter looks up through CaseTable, and the
// compiler emits these same numbers into the generated C. One table means the two cannot drift
// apart — see tools/gen-case-table.cs for why that is built in rather than tested for.
//
// Each run is four ints — start, count, stride, delta — meaning: the `count` code points beginning
// at `start` and spaced `stride` apart each map to themselves plus `delta`. Runs are sorted by
// start and their spans never overlap, so a binary search for the last run with start <= cp finds
// the only candidate. Stride 2 earns its place on the Latin Extended-A pattern, where uppercase and
// lowercase alternate (Ā ā Ă ă …) and each parity is a run of its own.
//
// Unicode data as of .NET {{Environment.Version}}, invariant culture: {{upper.Count}} uppercase and
// {{lower.Count}} lowercase mappings, carried in {{upperRuns.Count}} + {{lowerRuns.Count}} runs.

namespace Cufet.Interpreter;

public static class CaseTableData
{
    /// <summary>The .NET version whose invariant casing this table was generated from.</summary>
    public const string SourceRuntime = "{{Environment.Version}}";


""");

EmitRuns(outFile, "UpperRuns", "lowercase → uppercase", upperRuns);
outFile.AppendLine();
EmitRuns(outFile, "LowerRuns", "uppercase → lowercase", lowerRuns);
outFile.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(OutPath)!);
File.WriteAllText(OutPath, outFile.ToString().ReplaceLineEndings("\n"));

Console.WriteLine($"upper: {upper.Count} mappings in {upperRuns.Count} runs");
Console.WriteLine($"lower: {lower.Count} mappings in {lowerRuns.Count} runs");
Console.WriteLine($"verified exact for all 1114112 code points and 200000 random strings");
Console.WriteLine($"wrote {OutPath} ({new FileInfo(OutPath).Length} bytes)");


// ── Helpers ─────────────────────────────────────────────────────────────────────────────────────

static int CodePointCount(string s)
{
    int n = 0;
    for (int i = 0; i < s.Length; i += char.IsSurrogatePair(s, i) ? 2 : 1) n++;
    return n;
}

static string Escape(string s) => string.Concat(s.EnumerateRunes().Select(r => $"U+{r.Value:X4}"));

// Greedy run building. ★ A stride-2 run SKIPS the code points between its members, so it must not
// be allowed to span one that has a mapping of its own — otherwise a later run would begin inside
// this run's range, and the binary search (which trusts that the last run starting at or before cp
// is the only candidate) would land on the wrong one and silently return cp unchanged. Refusing to
// extend across a member of the table keeps every span disjoint, which is what makes the search safe.
static List<(int start, int count, int stride, int delta)> BuildRuns(List<(int cp, int to)> table)
{
    var present = table.Select(x => x.cp).ToHashSet();
    var runs = new List<(int, int, int, int)>();
    int i = 0;
    while (i < table.Count)
    {
        int delta = table[i].to - table[i].cp;
        int bestLen = 1, bestStride = 1;
        foreach (int stride in (int[])[1, 2])
        {
            int len = 1, j = i + 1;
            while (j < table.Count
                   && table[j].cp == table[j - 1].cp + stride
                   && table[j].to - table[j].cp == delta
                   && (stride == 1 || !present.Contains(table[j - 1].cp + 1)))
                { len++; j++; }
            if (len > bestLen) { bestLen = len; bestStride = stride; }
        }
        runs.Add((table[i].cp, bestLen, bestStride, delta));
        i += bestLen;
    }
    return runs.Select(r => (r.Item1, r.Item2, r.Item3, r.Item4)).ToList();
}

static int Lookup(List<(int start, int count, int stride, int delta)> runs, int cp)
{
    int lo = 0, hi = runs.Count - 1, found = -1;
    while (lo <= hi)
    {
        int mid = (lo + hi) / 2;
        if (runs[mid].start <= cp) { found = mid; lo = mid + 1; } else hi = mid - 1;
    }
    if (found < 0) return cp;
    var (start, count, stride, delta) = runs[found];
    int offset = cp - start;
    if (offset > (count - 1) * stride || offset % stride != 0) return cp;
    return cp + delta;
}

static string MapString(List<(int start, int count, int stride, int delta)> runs, string s)
{
    var sb = new StringBuilder(s.Length);
    for (int i = 0; i < s.Length; i += char.IsSurrogatePair(s, i) ? 2 : 1)
        sb.Append(char.ConvertFromUtf32(Lookup(runs, char.ConvertToUtf32(s, i))));
    return sb.ToString();
}

static void EmitRuns(StringBuilder outFile, string name, string what, List<(int start, int count, int stride, int delta)> runs)
{
    outFile.AppendLine($"    /// <summary>{what}, as start/count/stride/delta quadruples ({runs.Count} runs).</summary>");
    outFile.AppendLine($"    public static readonly int[] {name} =");
    outFile.AppendLine("    [");
    for (int i = 0; i < runs.Count; i += 4)
    {
        var line = new StringBuilder("       ");
        foreach (var (start, count, stride, delta) in runs.Skip(i).Take(4))
            line.Append($" {start,7}, {count,4}, {stride}, {delta,6},");
        outFile.AppendLine(line.ToString());
    }
    outFile.AppendLine("    ];");
}
